services:
  - type: web
    name: vprint-pl
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000